add DarkLightToggle
decred/pi-ui pull request #370
Opened 2021-09-16 16:37 UTC by vibros68

This pull request add DarkLightToggle, that will replace the old simple toggle as the disccussion from [politeiagui issue #2497](https://github.com/decred/politeiagui/issues/2497)

![Screenshot from 2021-09-16 23-32-27](https://user-images.githubusercontent.com/84569563/133650608-498f15ba-38ee-4161-a680-59b485e492cd.png)

2021-09-17 13:45 UTC, amass01 requested changes
Needs some love

2021-09-17 13:45 UTC, amass01 commented on src/theme/lightTheme.js
> +  "color-primary-dark": "var(--color-blue-darkest)",
Hrmm don't change theme variables values this affects so many other places also in `pigui`.

I guess you want to create new theme variables which are specific to your components needs
then use these in css styling to apply custom colors.

2021-09-17 13:46 UTC, amass01 commented on src/theme/darkTheme.js
> +  "text-color": "var(--color-blue-darker)",
Same here

2021-09-17 13:53 UTC, amass01 commented on src/components/Toggle/DarkLightToggle.jsx
> +
extra empty line

2021-09-17 14:04 UTC, amass01 requested changes
As mentioned on matrix: 
```
just noticed `src/components/Toggle/DarkLightToggle.jsx`  is wrong - you are using the 
native toggle styling file, your component is a new component which needs a separate 
new dir.
also, please add the new component to the docz and some basic tests like all other components.
```

2021-09-28 09:09 UTC, amass01 requested changes
Hitting the following when visiting docz DarkLightToggle page:

![image](https://user-images.githubusercontent.com/10324528/135058512-00d36bdd-40b2-4864-9e0b-cd3be5f42afd.png)

2021-09-28 09:34 UTC, amass01 requested changes
Wrap the JS code inside the `.mdx` file with the following:

![image](https://user-images.githubusercontent.com/10324528/135062503-c290da7e-c121-4073-acd4-cb685c29f8e3.png)

2021-09-30 11:18 UTC, amass01 approved these changes
LGTM

2021-09-30 12:11 UTC, tiagoalvesdulce approved these changes
ACK

2021-09-30 12:12 UTC, merged