feat(ButtonIcon): implement clickable icon component
decred/pi-ui pull request #405
Opened 2021-11-29 17:30 UTC by tiagoalvesdulce

Closes #387 

<img width="99" alt="Screen Shot 2021-11-29 at 14 29 40" src="https://user-images.githubusercontent.com/13955303/143915088-a56395fa-2c32-4baa-95d5-3e74217a50d6.png">

2021-11-29 18:42 UTC, bgptr requested changes
Overall looking good, only noticed these issues:
- styles are missing on the disabled state. Cursor, hover and colors stay the same.
- spinner is not visible (white on white background) in loading state:
<img width="47" alt="image" src="https://user-images.githubusercontent.com/52497040/143924021-08c2d4de-9077-4608-81b9-299abbdbcdf3.png">

2021-11-29 18:43 UTC, tiagoalvesdulce commented
Oh, I completely forgot to implement the disabled state

2021-11-30 10:07 UTC, bgptr commented
Looks cool. Just one more thing. The darker icon color should be lighter in the disabled state:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/52497040/144027175-dd463c75-4ebb-4f7a-98b6-d8f54bb28b8d.png">

2021-11-30 14:27 UTC, bgptr reviewed
just one little inline nit, but otherwise LGTM

2021-11-30 14:27 UTC, bgptr commented on src/theme/lightTheme.js
> +  "button-icon-color-1-disabled": "var(--color-gray-light",
missing close parenthesis

2021-12-01 13:14 UTC, bgptr approved these changes

2021-12-01 18:07 UTC, amass01 approved these changes
LGTM.

One general  question: why do we need `style` prop if we have `className` ?
I guess for backward compatibility in decrediton ?

2021-12-02 12:25 UTC, tiagoalvesdulce commented
@bgptr I'm thinking about ditching the `style` prop to encourage the usage of `className` as per conversation with `amass` on matrix. Do you this is important for Decrediton anyhow?

2021-12-02 13:16 UTC, bgptr commented
@tiagoalvesdulce It's not used, go for it.

2021-12-06 14:22 UTC, merged